# Generated by Django 5.1 on 2024-09-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
